sudo: required
os: linux
dist: focal

language: ruby

before_install:
  - sudo apt purge docker -y
  - sudo apt-get update
  - sudo apt-get install ca-certificates curl
  - sudo install -m 0755 -d /etc/apt/keyrings
  - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - sudo chmod a+r /etc/apt/keyrings/docker.asc
  - sudo apt install docker.io -y
  - gem install rubygems-update -v 3.4.22
  - sudo docker pull carlad/sinatra
  - sudo docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - sudo docker ps -a
  - sudo docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
- bundle exec rake test
