sudo: required
os: linux
dist: focal

language: ruby

before_install:
  - sudo apt-get update
  - sudo apt install -y docker.io
  - sudo systemctl enable --now docker
  - gem install rubygems-update -v 3.4.22
  - sudo docker pull carlad/sinatra
  - sudo docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - sudo docker ps -a
  - sudo docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
- bundle exec rake test
