sudo: required
os: linux
dist: focal

language: ruby

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt install -y docker.io
  - gem install rubygems-update -v 3.4.22
  - docker pull carlad/sinatra
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
- bundle exec rake test
