sudo: required
os: linux
dist: bionic
rvm: 2.6.3

language: ruby

before_install:
- sudo docker pull carlad/sinatra
- sudo docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- sudo docker ps -a
- sudo docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
- bundle exec rake test
